### ISSUE TITLE
Implement RDLFormatCode in name property

### ISSUE THREAD

**Issue by pdonahue-ventana** [SystemRDL/RALBot-html#11]
Given this file:
```
addrmap mymap {
  reg {
    name = "[b]Bold[/b] and [i]Italics[/i]";
    field {
      name = "[u]underline[/u]";
    } f[3];
  } foo;
};
```

The RDLFormatCode string shows up raw when I display the HTML.  When I grep for "Italics" I see that it was not transformed:
```
content/1.html:<h1>[b]Bold[/b] and [i]Italics[/i]</h1>
content/0.html:        <td>[b]Bold[/b] and [i]Italics[/i]</td>
```

The compiler's rdlfc_to_html function in rdlformatcode.py does appear to work properly (in a brief standalone test I did) but apparently that isn't being called.

**Comment by amykyta3** [comment]
Thank you for reporting.

You are correct that the "name" property isn't passed through the RDL format code processor.
If you try using the "desc" property, that does honor RDLFormatCode. I can't remember my exact reasoning but believe I omitted it from the "name" property since those are typically reserved for short user-friendly strings that rarely warrant any formatting.

I'd be interested in understanding your use-case and wouldn't mind adding some level of support.

**Comment by pdonahue-ventana** [comment]
The SystemRDL spec says that formatting in the name property is supposed to be supported:
> The RDLFormatCode tags shall be interpreted by the SystemRDL compiler and rendered in the generated output.
> These tags are only interpreted within the name and desc properties in SystemRDL

That being said, formatting in the name property is nice-to-have but definitely not must-have for me.  I do not have any existing SystemRDL that includes formatting and I was just starting to play with adding formatting now so I can work within any limitations.

Thanks.

**Comment by amykyta3** [comment]
Fair point. I'm not a huge fan of formatting in the `name` properties but I can implement at least a subset of this. Some of the spec [designers' decisions about RDLFormatCode are pretty baffling](https://systemrdl-compiler.readthedocs.io/en/latest/dev_notes/rdl_spec_errata.html#existence-of-the-rdlformatcode-desc-tag-seems-misguided).

I think its fair to at least implement the text formatting tags. Paragraph, bullet lists, and other block formatting tags seem inappropriate to use in a `name` string so I have little motivation to implement them here.

If you're interested, I also run the `desc` text through a Markdown processor. It has proven to be a much more readable way to format text since Markdown is far less intrusive.

**Comment by pdonahue-ventana** [comment]
> If you're interested, I also run the `desc` text through a Markdown processor. It has proven to be a much more readable way to format text since Markdown is far less intrusive.

I'll give that a try.  BBCode seems like a holdover from the 90's, back when blink tags were a big thing.
