### ISSUE TITLE
add signal table similar to field table for addrmap (feature request) 

### ISSUE THREAD

**Issue by kevbroch** [SystemRDL/RALBot-html#8]
Similar to the field table you already provide, have a signal table that has the various signal properties.

Simple example: 

Signal Name | Width | Description
-- | -- | --
clk | 1 |  
reset_n | 1 | reset all fields.

**Comment by amykyta3** [comment]
SystemRDL signals have somewhat of a bizzare scope lifetime compared to other hierarchical references. Rather than emitting the table at each usage of the object (as is done with enums), emit the signal description within the component it was instantiated.

Adding the table just before the "Contents" seems like a sane place to put it.

Since this is kinda outside the scope of a software spec, emitting signals will be disabled by default. Enable as an arg to the exporter.

Corner-case:
Signals instantiated to the root scope don't "belong" to any component. These will get propagated upwards to the addrmap being exported. Similarly, if the node being exported is not the top addrmap node, any other signals that are instantiated in any parents of the export node will also get included.
